### PR TITLE
Grade for Class 2 Assignment

### PR DESCRIPTION
**Pull request by ryansobol**
Good job, Terry. :sparkles: 
#### Exercise 1
- No crashes, works as expected. 4 points.
- Mind your whitespace between punctuation :space_invader: 
#### Exercise 2
- No crashes, works as expected. 4 points.
- Nice use of look-ahead regular expressions. +1 point.
- Here's the full [Oniguruma syntax](http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt) for Ruby
- Mind your whitespace between punctuation :space_invader: 
#### Exercise 3
- No crashes, works as expected. 4 points.
- Nice use of look-ahead regular expressions. +1 point.
- Mind your whitespace between punctuation :space_invader: 
#### Exercise 4
- No crashes, works as expected. 4 points.
#### Exercise 5
- No crashes, works as expected. 4 points.
- I don't think `STDOUT.flush` is needed as `puts` will [automatically flush the buffer](https://www.ruby-forum.com/topic/208856).
#### Exercise 6
- No crashes, works as expected. 4 points.
#### Exercise 7
- No crashes, but doesn't work as expected. 3 points.
- The `response` needs and `upcase`. :sweat: 
- I don't think `STDOUT.flush` is needed as `puts` will [automatically flush the buffer](https://www.ruby-forum.com/topic/208856).
#### Exercise 8
- No crashes, but doesn't work as expected. 3 points.
- The `linewidth` of the sample output is `50`. This is a pixel pushing exercise. :pushpin: 
- Mind your whitespace between punctuation :space_invader: 
- Nice usage of `Array`, `Symbol`, `to_proc`, `each_with_index`. +4 points.
#### Total

4 points: 6
3 points: 2

4 \* 6 + 3 \* 2 = 30
#### Bonus

4 points: 1
1 point: 2

4 \* 1 + 1 \* 2 = 6
#### Late Penalty

-4 points
#### Grand total

30 + 6 - 4 = 32 :star:

### CODE REVIEW

**Comment by terrydievendorf** [comment]
Ryan,
Thanks for the detailed feedback.  I appreciate it!

I will do a better job minding my whitespace from now on.  The Codefellows Javascript class has got me adding spaces :(

And, thanks for the link to the Oniguruma syntax.

-Terry

**Comment by terrydievendorf** [comment]
Ryan,
Could you show me how the whitespace should be for Exercise 1.  I'm confused by the fact that Chris Pine seems to do what I'm doing as far as I can tell, and I'm not sure what you're expecting.

Thanks!
Terry

**Comment by ryansobol** [comment]
My bad, your solution for exercise 1 looks fine. I was probably looking at your solution for exercise 2 when I wrote that. :sleeping:

**Comment by terrydievendorf** [comment]
Umm... Can you tell me where the whitespace should change in Exercise 2?  :)

Thanks!

**Comment by ryansobol** [comment]
``` ruby
# bad
(60 * 24 *365 *10)

# good
(60 * 24 * 365 * 10)
```

``` ruby
# bad
gsub(/...(?=.)/,'\&,')

# good
gsub(/...(?=.)/, '\&,')
```

**Comment by terrydievendorf** [comment]
Thanks again, Ryan.  See you tonight!

**Pull request closed without merging**
